const COPY = {
  sk: {
    halls: "Sály", now: "Teraz", retry: "Skúsiť znova", close: "Zavrieť",
    trailer: "Trailer", load: "Načítavam program…",
    err: "Program sa nepodarilo načítať. Ak otváraš súbor priamo, spusť ho cez lokálny server.",
    empty: "Na tento deň nič neostalo — uprav filtre alebo vyber iný deň.",
    emptyFav: "Na tento deň nemáš obľúbené. Označ predstavenie hviezdičkou.",
    emptySearch: "Nič sa nenašlo.",
    sections: "Sekcie", venues: "Sály", more: "Celý text",
    program: "Program", clearAll: "Zrušiť všetko", clearSel: "Zrušiť výber",
    showN: (n) => n === 1 ? "Zobraziť 1 položku" : "Zobraziť " + COPY.sk.films(n),
    searchPh: "Hľadať film, sálu, sekciu…", langLabel: "Jazyk",
    favs: "Obľúbené", favAdd: "Pridať k obľúbeným", favRemove: "Odstrániť z obľúbených",
    grid: "Mriežka", list: "Zoznam", search: "Hľadať", filters: "Filtre",
    settings: "Nastavenia",
    tickets: "Vstupenky", ticketsHint: "Zaškrtni vstupenky, ktorými chceš rezervovať. QR ostane v telefóne; pri rezervácii sa kód odošle do Invitonu.",
    resBtn: "Rezervovať", resDone: "Rezervované", resNeed: "Pridaj vstupenku",
    resNoPass: "Rezervácie fungujú cez tvoju akreditáciu alebo vstupenku. Najprv naskenuj jej QR kód – ostane len v telefóne.",
    resNeedHint: "Na rezerváciu najprv pridaj vstupenku.",
    resUnresAsk: "Zrušiť rezerváciu? Miesto sa môže medzitým obsadiť.",
    resFree: (n) => `voľné miesta: ${n}`,
    resPasses: (n) => n + (n >= 2 && n <= 4 ? " vstupenky" : " vstupeniek"),
    ticketDeleted: "Vstupenka zmazaná.", undo: "Späť",
    favAdded: "Pridané k obľúbeným", favRemoved: "Odstránené z obľúbených",
    qrFail: "QR kód sa nepodarilo vykresliť. Kód vstupenky:",
    clearQuery: "Vymazať hľadanie", goProgram: "Späť na program", clearFilters: "Zrušiť filtre",
    resFavs: "Rezervovať obľúbené", resMine: "Rezervácie", resMineEmpty: "Zatiaľ žiadna rezervácia.",
    share: "Zdieľať", shareTitle: "Zdieľať obľúbené",
    shareHint: "Odkaz obsahuje tvoje meno a predstavenia. Ukáž QR kód alebo ho pošli.",
    shareName: "Tvoje meno", shareNamePh: "Napr. Tomáš",
    shareCopy: "Kopírovať odkaz", shareDo: "Zdieľať odkaz", shareLink: "Odkaz",
    shareQr: "QR kód so zoznamom obľúbených",
    shareQrHint: "Ukáž kód kamarátovi. Naskenuje ho fotoaparátom — bez chatu aj offline.",
    shareQrFail: "QR kód sa nepodarilo vykresliť. Použi odkaz.",
    shareCopied: "Odkaz je v schránke.", shareEmpty: "Najprv si označ obľúbené.",
    shareFail: "Odkaz sa nepodarilo skopírovať. Označ ho v poli a skopíruj ručne.",
    shareClose: "Zavrieť zoznam",
    sharedBanner: (name) => name ? `Obľúbené: ${name}` : "Kamarátov zoznam",
    emptyShared: "Na tento deň v tomto zozname nič nie je.",
    resUse: "Rezervovať s touto vstupenkou",
    resBusy: "Rezervujem…", resOk: "Rezervované.", resUnresOk: "Rezervácia zrušená.",
    resUnres: "Zrušiť rezerváciu", resLog: "Výsledok rezervácií",
    resNo: "Toto predstavenie nie je v rezervačnom systéme.",
    resBadPass: "Túto vstupenku Inviton nepozná. Skontroluj naskenovaný QR.",
    resFail: "Rezervácia sa nepodarila.", resSkip: "Už rezervované",
    resR1: "Málo kreditov.", resR2: "Kapacita je plná.",
    resR3: "Táto vstupenka na rezerváciu nestačí.", resR4: "Predstavenie sa nedá rezervovať.",
    resR5: "Rezerváciu už nie je možné spraviť ani zrušiť.",
    resFavAsk: (n, m) => `Rezervovať ${n} obľúbených pre ${m} ${m === 1 ? "vstupenku" : "vstupenky"}?`,
    addTicket: "Pridať vstupenku", scanQr: "Skenovať QR", scanFile: "Zo súboru",
    stopScan: "Zastaviť sken", ticketName: "Názov vstupenky", saveTicket: "Uložiť",
    showTicket: "Zobraziť QR", deleteTicket: "Zmazať", noTickets: "Zatiaľ žiadna vstupenka.",
    ticketSel: "Vstupenka", scanNeedHttps: "Kamera potrebuje HTTPS alebo localhost.",
    scanFail: "Skenovač sa nepodarilo spustiť.", scanLib: "Načítavam skener…",
    scanNoQr: "V súbore sa nenašiel QR kód.",
    ticketSaved: "Vstupenka uložená.", namePh: "Napr. Moja akreditácia",
    scanOk: "Naskenované. Zadaj názov a ulož.", showQr: "Zobraziť QR",
    rateWait: "Načítavam hodnotenia…",
    name: "Cinematik v mobile",
    disclaimer: "Neoficiálny pomocník na festival (8.–13. 9. 2026). Nie je to oficiálna aplikácia MFF Cinematik.",
    foot: "Zdroj: Inviton EventSchedulePublic · ",
    ideas: "Nápady",
    notify: "Upozornenia",
    notifyHint: "Funguje, keď je aplikácia otvorená. Na nainštalovanej PWA na Androide aj na pozadí.",
    notifyOn: "Upozorniť pred filmom",
    notifyMins: "Minút pred začiatkom",
    notifyOnFav: "Obľúbené",
    notifyOnRes: "Rezervované",
    notifyNo: "Tento prehliadač upozornenia nepodporuje.",
    notifyDenied: "Upozornenia sú v prehliadači vypnuté.",
    notifyFav: "Obľúbené",
    notifyRes: "Rezervácia",
    notifyBody: (mins, hall, kind) => ["Za " + mins + " min", hall, kind].filter(Boolean).join(" · "),
    films: (n) => n + " " + (n === 1 ? "položka" : n >= 2 && n <= 4 ? "položky" : "položiek"),
    today: "dnes", about: "O aplikácii", sound: "Zvuk", soundOn: "Zvuk počas načítavania",
    days: ["nedeľa", "pondelok", "utorok", "streda", "štvrtok", "piatok", "sobota"],
    daysShort: ["ne", "po", "ut", "st", "št", "pi", "so"],
    brow: "MFF Piešťany · 8.–13. 9. 2026",
  },
  en: {
    halls: "Venues", now: "Now", retry: "Try again", close: "Close",
    trailer: "Trailer", load: "Loading programme…",
    err: "Could not load the programme. Serve this file over HTTP if you opened it from disk.",
    empty: "Nothing left for this day — change filters or pick another day.",
    emptyFav: "No favourites this day. Star a screening to save it.",
    emptySearch: "No matches.",
    sections: "Sections", venues: "Venues", more: "Full text",
    program: "Programme", clearAll: "Clear all", clearSel: "Clear",
    showN: (n) => "Show " + COPY.en.films(n),
    searchPh: "Search film, venue, section…", langLabel: "Language",
    favs: "Favourites", favAdd: "Add to favourites", favRemove: "Remove from favourites",
    grid: "Grid", list: "List", search: "Search", filters: "Filters",
    settings: "Settings",
    tickets: "Tickets", ticketsHint: "Tick the passes you want to reserve with. The QR stays on the phone; it is sent to Inviton only when you reserve.",
    resBtn: "Reserve", resDone: "Reserved", resNeed: "Add a pass",
    resNoPass: "Reservations work through your pass or ticket. Scan its QR code first – it stays on this phone.",
    resNeedHint: "Add a pass to reserve.",
    resUnresAsk: "Cancel the reservation? The seat may be taken in the meantime.",
    resFree: (n) => `seats left: ${n}`,
    resPasses: (n) => `${n} passes`,
    ticketDeleted: "Pass deleted.", undo: "Undo",
    favAdded: "Added to favourites", favRemoved: "Removed from favourites",
    qrFail: "Could not draw the QR code. Pass code:",
    clearQuery: "Clear search", goProgram: "Back to programme", clearFilters: "Clear filters",
    resFavs: "Reserve favourites", resMine: "Reservations", resMineEmpty: "No reservations yet.",
    share: "Share", shareTitle: "Share favourites",
    shareHint: "The link carries your name and screenings. Show the QR code or send it.",
    shareName: "Your name", shareNamePh: "e.g. Tomas",
    shareCopy: "Copy link", shareDo: "Share link", shareLink: "Link",
    shareQr: "QR code of your favourites",
    shareQrHint: "Show the code to a friend. They scan it with the camera — no chat, works offline.",
    shareQrFail: "Could not draw the QR code. Use the link instead.",
    shareCopied: "Link copied.", shareEmpty: "Star some screenings first.",
    shareFail: "Could not copy the link. Select it in the field and copy it yourself.",
    shareClose: "Close list",
    sharedBanner: (name) => name ? `Favourites: ${name}` : "A friend's list",
    emptyShared: "Nothing from this list on this day.",
    resUse: "Use this pass for reservations",
    resBusy: "Reserving…", resOk: "Reserved.", resUnresOk: "Reservation cancelled.",
    resUnres: "Cancel reservation", resLog: "Reservation results",
    resNo: "This screening is not in the reservation system.",
    resBadPass: "Inviton does not recognise this pass. Check the scanned QR.",
    resFail: "Reservation failed.", resSkip: "Already reserved",
    resR1: "Not enough credits.", resR2: "Sold out.",
    resR3: "This pass cannot reserve that screening.", resR4: "Screening cannot be reserved.",
    resR5: "Too late to reserve or cancel.",
    resFavAsk: (n, m) => `Reserve ${n} favourites for ${m} pass${m === 1 ? "" : "es"}?`,
    addTicket: "Add ticket", scanQr: "Scan QR", scanFile: "From file",
    stopScan: "Stop scan", ticketName: "Ticket name", saveTicket: "Save",
    showTicket: "Show QR", deleteTicket: "Delete", noTickets: "No tickets yet.",
    ticketSel: "Ticket", scanNeedHttps: "Camera needs HTTPS or localhost.",
    scanFail: "Could not start the scanner.", scanLib: "Loading scanner…",
    scanNoQr: "No QR code found in that file.",
    ticketSaved: "Ticket saved.", namePh: "e.g. My pass",
    scanOk: "Scanned. Name it and save.", showQr: "Show QR",
    rateWait: "Loading ratings…",
    name: "Cinematik v mobile",
    disclaimer: "Unofficial festival helper (8–13 Sep 2026). Not an official MFF Cinematik app.",
    foot: "Source: Inviton EventSchedulePublic · ",
    ideas: "Ideas",
    notify: "Alerts",
    notifyHint: "Works while the app is open. Installed Android PWAs can also alert in the background.",
    notifyOn: "Remind me before a film",
    notifyMins: "Minutes before the start",
    notifyOnFav: "Favourites",
    notifyOnRes: "Reservations",
    notifyNo: "This browser does not support notifications.",
    notifyDenied: "Notifications are blocked in the browser.",
    notifyFav: "Favourite",
    notifyRes: "Reserved",
    notifyBody: (mins, hall, kind) => ["In " + mins + " min", hall, kind].filter(Boolean).join(" · "),
    films: (n) => n + " item" + (n === 1 ? "" : "s"),
    today: "today", about: "About", sound: "Sound", soundOn: "Sound while loading",
    days: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
    daysShort: ["Su", "Mo", "Tu", "We", "Th", "Fr", "Sa"],
    brow: "IFF Piešťany · 8–13 Sep 2026",
  },
};

const SEC_HUE = {
  "Meeting Point Europe": 70,
  "Cinematik.doc": 210,
  "Rešpekt: Nils Malmros": 145,
  "Other Spaces": 300,
  "Cinematik Junior": 95,
  "Sprievodné podujatia": 40,
  "Dánsko pod lupou": 25,
  "Slovenský horizont": 255,
  "Cinematik Classics": 80,
  "DoKma": 185,
  "Za hranicou kultu: …prichádza tma": 15,
  "Cesty slávy": 230,
};

export { COPY, SEC_HUE };
